version: "3"
services:
    db:
        container_name: psql
        restart: always
        image: psql
        container_name: 'my_site_db'
        build:
            context: ./db
        volumes:
            - ./db/data/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres  # To be moved to environment file
            POSTGRES_DATABASE: myrest
            SSLMODE: disable
        expose:
            - 5432
        ports:
            - 5432:5432
        networks:
            - psql-pgql
    go-docker-image:
        image: mrsedan/go-rest-api
        container_name: 'my_site_backend'
        restart: always
        build: ./backend
        ports: 
            - '8080:8080'
        volumes: 
            - ./backend:/app
        depends_on: 
            - db
    
networks:
    psql-pgql: